"""add auth

Revision ID: 1b15a66d56a8
Revises: 27a37b21069c
Create Date: 2023-08-02 12:57:48.619840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b15a66d56a8'
down_revision = '27a37b21069c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
