"""add year

Revision ID: 27a37b21069c
Revises: fc92bd2caeda
Create Date: 2023-08-01 13:39:56.451036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a37b21069c'
down_revision = 'fc92bd2caeda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'year')
    # ### end Alembic commands ###
