"""add auth2

Revision ID: 568937018d50
Revises: 1b15a66d56a8
Create Date: 2023-08-02 13:00:12.264825

"""
from alembic import op
from fastapi_users_db_sqlalchemy.generics import GUID
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568937018d50'
down_revision = '1b15a66d56a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default=sa.text("'No name given'"), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
